### ISSUE TITLE
shield docs don't exist here yet

### ISSUE THREAD

**Issue by gregglind** [mozilla/firefox-data-docs#4]
Also, sadly, I have to write such things.  Or not.  Ideas welcome, plz reframe this into an actionable bug @harterrt 🥇 

Or task me on something else :)

**Comment by harterrt** [comment]
This bug is probably blocked by [Bug 1341812](https://bugzilla.mozilla.org/show_bug.cgi?id=1341812) which asks for a high level overview of our tools for experimentation. With that bug complete we can scope the documentation we need specifically for shield.

On the other hand, if we have some cycles to work on this from the bottom up, some simple high level docs on shield would be useful. For example, a page describing the following would be useful:

* What shield is meant to do, what it now does
* Where to read more about the implementation
* Who to ask questions to 

To my knowledge this documentation doesn't exist yet, here or elsewhere. Let me know if I'm wrong and we can just link to that.

**Comment by gregglind** [comment]
Yes, this is a drag :)  Keep poking me.  I am trying to work on it, and not sure what stuff is going to continue to exist.

**Comment by wlach** [comment]
Same resolution applies here as in https://bugzilla.mozilla.org/show_bug.cgi?id=1341812 I think (this bug is old, we now do have some documentation...). New bugs can be opened if deficiencies are found.
